### ISSUE TITLE
Not an Issue, but a thank you

### ISSUE THREAD

**Issue by sator-arepo** [pquaid/pcq#1]
Dear Patrick,

around 25 years ago I used PCQ on my Amiga, having learned Turbo Pascal in school. I liked it and learned quite a bit by looking at your source code. Thank you for putting the source here an GitHub, I just found it today and nostalgically think about those good old days. Just out of curiosity, there used to be the Peep optimizer, apparently the source has not been included. Will you add that as well?

Thank you from Germany!

**Comment by sator-arepo** [comment]
Don't bother, I found it (in examples).

**Comment by pquaid** [comment]
Ah, good. I was pretty sure I had scraped every last file that I had, and in any case I've since sold the machine.

Thanks for the kind words. Posting this was definitely a nostalgia trip for me, too!
